version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: chai
    versions:
    - 4.3.3
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
